// DEVELOPMENT DATA ONLY. No real commercial offers, contacts or verified shops.
import type { Catalogue, Variant } from './model.ts';
const variants = (price: number, sizes: string[], color: string): Variant[] =>
  sizes.map((size, index) => ({
    id: color + '-' + size,
    size,
    color,
    available: index !== sizes.length - 1 || sizes.length === 1,
    price,
  }));
export const fixtureCatalogue: Catalogue = {
  mode: 'fixtures',
  shops: [
    {
      slug: 'demo-atelier',
      name: 'Atelier',
      category: 'Женская одежда',
      mall: 'Пример ТЦ · центр',
      image: '/dev-fixtures/interior.jpg',
      description:
        'Демонстрационный бутик: лаконичные вещи, натуральные оттенки и внимание к деталям. Не является реальным магазином.',
      status: 'ACTIVE',
    },
    {
      slug: 'demo-form',
      name: 'FORM',
      category: 'Одежда и обувь',
      mall: 'Пример ТЦ · юг',
      image: '/dev-fixtures/boutique-men.png',
      description:
        'Демонстрационный магазин повседневной одежды и обуви. Предложения приведены для знакомства с интерфейсом.',
      status: 'ACTIVE',
    },
    {
      slug: 'demo-objects',
      name: 'Objects',
      category: 'Аксессуары и ароматы',
      mall: 'Пример ТЦ · центр',
      image: '/dev-fixtures/boutique-bags.png',
      description:
        'Демонстрационная коллекция аксессуаров и ароматов. Контакты и реальные предложения пока не подключены.',
      status: 'ACTIVE',
    },
    {
      slug: 'demo-beauty',
      name: 'Beauty room',
      category: 'Косметика и парфюмерия',
      mall: 'Пример ТЦ · центр',
      image: '/dev-fixtures/boutique-beauty.png',
      description:
        'Демонстрационный бутик косметики. Изображение сгенерировано для проверки интерфейса, реальных предложений и контактов нет.',
      status: 'ACTIVE',
    },
    {
      slug: 'demo-hidden',
      name: 'Скрытый магазин',
      category: 'Одежда',
      mall: '',
      image: '/dev-fixtures/coat.jpg',
      description: 'Fixture проверки непубличного статуса.',
      status: 'SUSPENDED',
    },
  ],
  products: [
    {
      slug: 'demo-sand-coat',
      name: 'Пальто свободного кроя',
      description:
        'Спокойный силуэт для повседневного гардероба. Демонстрационная карточка: фотография иллюстративная, состав и характеристики реального товара не подтверждены.',
      category: 'women',
      subcategory: 'Верхняя одежда',
      brand: 'Atelier · демо',
      shop: 'demo-atelier',
      image: '/dev-fixtures/coat.jpg',
      imageAlt: 'Светлое пальто — иллюстрация демонстрационного товара',
      price: 64900,
      isNew: true,
      variants: variants(64900, ['S', 'M', 'L'], 'Бежевый'),
    },
    {
      slug: 'demo-everyday-bag',
      name: 'Сумка на каждый день',
      description:
        'Акцентная деталь повседневного образа. Это демонстрационный товар, не предложение о продаже.',
      category: 'accessories',
      subcategory: 'Сумки',
      brand: 'Objects · демо',
      shop: 'demo-objects',
      image: '/dev-fixtures/bag.jpg',
      imageAlt: 'Коричневая сумка — иллюстрация демонстрационного товара',
      price: 32900,
      oldPrice: 39900,
      isNew: false,
      variants: variants(32900, ['Один размер'], 'Коричневый'),
    },
    {
      slug: 'demo-city-sneakers',
      name: 'Кеды для города',
      description:
        'Пара для прогулок в своём ритме. Демонстрационный товар; материалы и наличие реального изделия не подтверждены.',
      category: 'shoes',
      subcategory: 'Кеды',
      brand: 'FORM · демо',
      shop: 'demo-form',
      image: '/dev-fixtures/shoes.jpg',
      imageAlt: 'Белые кеды — иллюстрация демонстрационного товара',
      price: 28900,
      isNew: true,
      variants: variants(28900, ['37', '38', '39', '40'], 'Белый'),
    },
    {
      slug: 'demo-signature-scent',
      name: 'Парфюмерная вода',
      description:
        'Аромат как часть личного стиля. Иллюстративная фотография, демонстрационные цена и описание. Не является предложением показанного бренда.',
      category: 'beauty',
      subcategory: 'Парфюмерия',
      brand: 'Objects · демо',
      shop: 'demo-objects',
      image: '/dev-fixtures/perfume.jpg',
      imageAlt: 'Флакон парфюма — иллюстрация демонстрационного товара',
      price: 45900,
      oldPrice: 52000,
      isNew: true,
      variants: variants(45900, ['50 мл'], 'Без цвета'),
    },
    {
      slug: 'demo-black-hoodie',
      name: 'Худи мужское',
      description:
        'Демонстрационный товар: мужская одежда. Изображение иллюстративное, не предложение о продаже.',
      category: 'men',
      subcategory: 'Худи',
      brand: 'FORM · демо',
      shop: 'demo-form',
      image: '/dev-fixtures/hoodie.png',
      imageAlt: 'Чёрное худи — иллюстрация демонстрационного товара',
      price: 34000,
      isNew: false,
      variants: variants(34000, ['M', 'L'], 'Чёрный'),
    },
    {
      slug: 'demo-classic-watch',
      name: 'Часы наручные',
      description:
        'Демонстрационные часы и украшения. Изображение иллюстративное, не предложение о продаже.',
      category: 'accessories',
      subcategory: 'Часы',
      brand: 'Objects · демо',
      shop: 'demo-objects',
      image: '/dev-fixtures/watch.png',
      imageAlt: 'Наручные часы — иллюстрация демонстрационного товара',
      price: 35000,
      isNew: false,
      variants: variants(35000, ['Один размер'], 'Золотистый'),
    },
    {
      slug: 'demo-evening-dress',
      name: 'Платье вечернее',
      description:
        'Демонстрационное вечернее платье. Изображение иллюстративное, не предложение о продаже.',
      category: 'women',
      subcategory: 'Платья',
      brand: 'Atelier · демо',
      shop: 'demo-atelier',
      image: '/dev-fixtures/dress.png',
      imageAlt: 'Бежевое платье — иллюстрация демонстрационного товара',
      price: 56000,
      isNew: false,
      variants: variants(56000, ['S', 'M'], 'Бежевый'),
    },
    {
      slug: 'demo-kids-set',
      name: 'Детский костюм',
      description:
        'Детские товары: демонстрационный комплект. Изображение иллюстративное, не предложение о продаже.',
      category: 'kids',
      subcategory: 'Детская одежда',
      brand: 'FORM · демо',
      shop: 'demo-form',
      image: '/dev-fixtures/kids.png',
      imageAlt: 'Детский комплект — иллюстрация демонстрационного товара',
      price: 30000,
      isNew: false,
      variants: variants(30000, ['104', '110'], 'Бежевый'),
    },
    {
      slug: 'demo-hidden-product',
      name: 'Непубличный товар',
      description: '',
      category: 'women',
      subcategory: 'Верхняя одежда',
      brand: 'Демо',
      shop: 'demo-hidden',
      image: '/dev-fixtures/coat.jpg',
      imageAlt: '',
      price: 1000,
      isNew: false,
      variants: variants(1000, ['S'], 'Бежевый'),
    },
  ],
};
